### ISSUE TITLE
Connector Configs Required

### ISSUE THREAD

**Issue by wkd368** [Aegeaner/kafka-connector-redis#1]
Hey, 

Can you please place sample config for this connector which will be used to register it?
It would be good if you can explain all config attributes for standalone and distributed with examples.

Thanks!

**Comment by Aegeaner** [comment]
You can checkout the config definition and default values for Redis Source: [https://github.com/Aegeaner/kafka-connector-redis/blob/1c6af9f1f26b5732fcabdad098ce28b8677c5175/src/main/java/org/apache/kafka/connect/redis/RedisSourceConfig.java#L41](https://github.com/Aegeaner/kafka-connector-redis/blob/1c6af9f1f26b5732fcabdad098ce28b8677c5175/src/main/java/org/apache/kafka/connect/redis/RedisSourceConfig.java#L41)
