### ISSUE TITLE
upgrade redis-replicator to recent version

### ISSUE THREAD

**Issue by leonchen83** [Aegeaner/kafka-connector-redis#4]
hi @Aegeaner 
Redis-replicator do a lot of changes in recent version.
The version 2.0.0-rc3 doesn't support rawValue, rawCommand.
Highly recommend upgrade redis-repicator to 2.5.0.

**Comment by leonchen83** [comment]
From redis-replicator-2.4.0
Redis-replicator support redis uri to construct `Configuration` more simpler.
More details please refer to [redis uri](https://github.com/leonchen83/redis-replicator#45-redis-uri)
  
Redis-replicator-2.5.0 support `DefaultCommand` and `DefaultCommandParser` to handle raw byte[] command. This is optional. More details please refer to [MigrationExample](https://github.com/leonchen83/redis-replicator/blob/master/examples/com/moilioncircle/examples/migration/MigrationExample.java)

**Comment by Aegeaner** [comment]
Thanks @leonchen83 ，I will consider upgrade the redis-replicator to 2.5.0 later after the Spring Festival.
