### ISSUE TITLE
How to compile this to a jar file?

### ISSUE THREAD

**Issue by realmarkcross** [Aegeaner/kafka-connector-redis#5]
How should I attempt to compile this code to a jar file?  I assume it's an uber jar correct?  When I try to compile as an uber jar it says that some of the dependencies are not available.  Would you mind providing some instructions to a non-Java guy?  Thanks.

**Comment by Aegeaner** [comment]
Have you even tried using `mvn package -DskipTests` ?

**Comment by realmarkcross** [comment]
Thanks for your help.  Here's the error:

Failed to execute goal on project kafka-connect-redis: Could not resolve dependencies for project org.apache:kafka-connect-redis:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.kafka:connect-api:jar:0.10.2.0-SNAPSHOT, org.apache.kafka:connect-runtime:jar:0.10.2.0-SNAPSHOT: Could not find artifact org.apache.kafka:connect-api:jar:0.10.2.0-SNAPSHOT -> [Help 1]

**Comment by Aegeaner** [comment]
Hi @masterGH , the reason is the SNAPSHOT version is gone with the maven repository. I have fixed this problem, just update your git repository and try again, thanks.
